### ISSUE TITLE
Improve the "submit issue" template

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#170]
### Description

It's a bit annoying that the `target library` is added as a list in the description instead of a label in the issue.

My suggestion is using something as: https://github.com/marketplace/actions/advanced-issue-labeler so it'd be a combo and it'd automatically label it accordingly.

Also, the same should be done for feature/bug: it should be a label, not appear in the title.

**Comment by cmin764** [comment]
Sounds good, we have labels for everything like this, no need to tag through the Issue name.

**Comment by cmin764** [comment]
Planning to do the following:
- Removing the issue title tag (`[Issue]` `[Feature]`). -> will use labels for this
- Removing the dropdown/selection of libs in favor to manual labeling, as it seems there's non-trivial work to be done to bring label automation while avoiding redundancy; there's also maintenance to do with every newly added package. (see below a potential bring-back if we find a satisfiable easy way to do it)

Potential dropdown with the affected package:
```yaml
  - type: dropdown
    id: library
    attributes:
      label: Target library
      description: Select the affected packages in the reported bug (if any)
      multiple: true
      options:
        - N/A (Default)
        - Action Server (action_server)
        - actions
```
