### ISSUE TITLE
The `.select()` doesn't work on Notepad in Windows 11 everywhere

### ISSUE THREAD

**Issue by cmin764** [robocorp/robocorp#172]
### What happened?

When trying to change the font name/style/size with the low-level `Select` method (invoked with `.select()`) of such combobox element, the selection happens successfully, but the new value doesn't get set nor visible. It happens with the entries which can be completed by also typing text inside. E.g.:

- Works well with the font style.
- But doesn't work with the font family or size.

Related [example workaround](https://github.com/robocorp/example-windows-notepad/blob/master/tasks.py#L66-L68).

I remember this [was working](https://github.com/robocorp/rpaframework/blob/master/packages/windows/tests/robot/test_windows.robot#L253) just fine in RPA Framework. Maybe that's not the case anymore, should test thoroughly first!

### System Info

_conda.yaml_
```yaml
# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - pip:
    - robocorp==1.4.3             # https://pypi.org/project/robocorp
    - robocorp-windows==1.0.1     # https://pypi.org/project/robocorp-browser
```

Discovered while converting from RF to Python this [example](https://github.com/robocorp/example-windows-notepad/pull/4/files#diff-2e746c9eacad6e2c2fdefdc6a665b5ce4607ea384ebf97a729044b79acc778d6R29-R34).

<img width="1246" alt="Screenshot 2024-01-18 at 7 45 01 PM" src="https://github.com/robocorp/robocorp/assets/709053/8d2c9518-e504-4b27-906a-dff91620ee3d">
