### ISSUE TITLE
`workitems.outputs.create` does not support `Path`-like inputs for the `files` parameter

### ISSUE THREAD

**Issue by kylie-bee** [robocorp/robocorp#193]
### Target library

- [ ] Action Server
- [ ] robocorp-actions
- [ ] robocorp-browser
- [ ] robocorp-tasks
- [ ] robocorp-vault
- [ ] robocorp-windows
- [X] robocorp-workitems

### What happened?

`workitems.output.create` has a parameter `files` that has a type hint of `Optional[Union[str, list[str]]]` but as it is expecting paths, it should accept `pathlib.Path`-like objects.

### System Info

conda.yaml:

```yaml
channels:
  - conda-forge

dependencies:
  - python=3.10.13 # https://pyreadiness.org/3.10

  # DEV dependencies
  - pytest=7.4.4

  - pip=23.2.1 # https://pip.pypa.io/en/stable/news
  - truststore=0.8.0 # https://pypi.org/project/truststore
  - pip:
      - robocorp==1.6.0 # https://pypi.org/project/robocorp
      - robocorp-log-pytest==0.0.3 # https://pypi.org/project/robocorp-log-pytest
      - hubspot-api-client==8.2.1 # https://pypi.org/project/hubspot-api-client
      - robocorp-planhat==0.4.3 # https://pypi.org/project/robocorp-planhat
```
