### ISSUE TITLE
Failed Work Items don't produce error logs (hard to discover through logs when an item failed)

### ISSUE THREAD

**Issue by cmin764** [robocorp/robocorp#256]
### Target components

log, workitems

### What is wrong

When handling exceptions (without raising explicitly) I don't see it in the logs. (maybe feature, not a bug)

But as soon as I `log.exception()` the caught error, I end up with two red error messages in the log (logging the error **twice**).

----

Not sure if this is really a bug, but this stemmed from the fact that `.fail()` Work Items didn't produce any error in the output log and you had to unfold all the processed input items until the leaf to see what was released as `FAIL` and what as `DONE`.

### System info

Platform-agnostic, used the following _conda.yaml_ (latest versions at the moment of test):

```yaml
channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip:
    - rpaframework==28.2.0        # https://rpaframework.org/releasenotes.html
    - robocorp==1.6.2             # https://pypi.org/project/robocorp
    - robocorp-browser==2.2.2     # https://pypi.org/project/robocorp-browser
```

### Example script

I just used our [**template-python-workitems**](https://github.com/robocorp/template-python-workitems) to discover the problem, mainly under these lines:

```python
try:
            name = item.payload["Name"]
            zipcode = item.payload["Zip"]
            product = item.payload["Product"]
            print(f"Processing order: {name}, {zipcode}, {product}")
            # assert 1000 <= zipcode <= 9999, "Invalid ZIP code"
            if not 1000 <= zipcode <= 9999:
                raise ValueError(f"Invalid ZIP code: {zipcode}")  # produces error log every time (because we raise explicitly)
            workitems.outputs.create(payload={"Order": f"{name} is complete"})
            item.done()
        except ValueError as err:
            item.fail("BUSINESS", code="INVALID_ORDER", message=str(err))
            log.warn(err)  # produces one warning as expected
        except KeyError as err:
            item.fail("APPLICATION", code="MISSING_FIELD", message=str(err))
            log.exception(err)  # logs twice the exception (and nothing in its absence)
```

----

So maybe the problem here is not with the logging, but with the fact that `WorkItem.fail()` doesn't produce any additional error log with it. And that might be the solution here, something we already have in `RPA.Robocorp.WorkItems` ([logging](https://github.com/robocorp/rpaframework/blob/master/packages/main/src/RPA/Robocorp/WorkItems.py#L238-L245) the failure as well when it gets released with such state).
