### ISSUE TITLE
Support for receiving secrets

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#327]
### Target components

action_server

### Why & who

We'd like an external source to pass secrets to the action server in a way that it's possible to know which secrets are expected.

In dev mode secrets should be received in the `input.json` and in production mode they should be in the `x-action-context` header.

### Feature or enhancement

The expected user API in actions is something as:

```python

from robocorp.actions import Request, Secret, OAuthUserSecret

@action
def compare_time_zones(
	user_timezone: str, 
	request: Request, 
	google_oauth_secret: OAuthSharedSecret,
	my_oauth_secret: OAuthUserSecret,
	google_username: Secret,
	google_password: Secret,
	) -> str:	
		print(google_oauth_secret.access_token)
		print(google_oauth_secret.refresh_token)

		print(google_username.value)

```

Initially only the `Secret` (simple string) will be implemented.

`action-server package metadata` should be able to extract information from the action and generate a `metadata.json` with something as:

```
metadata:
  secrets:
    <url-for-secret>:
      action: <action-name>
      actionPackage: <action-package-name>
      secrets:
        <secret-name>:
          type: Secret
```

Example:

```
metadata:
  secrets:
    /api/actions/pack-secrets/hello/run:
      action: hello
      actionPackage: pack_secrets
      secrets:
        private_info:
          type: Secret
```
